Ecommerce/Ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include
from . import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('shop.urls')),
    path('search/',include('search.urls')),
    path('cart/',include('cart.urls')),


]


urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

Ecommerce/cart/urls.py
from django.contrib import admin
from django.urls import path
from cart import views

app_name='cart'
urlpatterns = [
   path('add_to_cart/<int:pk>',views.add_to_cart,name="add_to_cart"),
   path('cart_views',views.cart_views,name="cart_views"),
   path('cart_decrement/<int:pk>',views.cart_decrement,name="cart_decrement"),
   path('delete/<int:pk>',views.delete,name="delete"),
   path('place_order',views.place_order,name="place_order"),
   path('payment_status/<u>',views.payment_status,name="payment_status"),
   path('orderview',views.orderview,name="orderview"),
]

Ecommerce/search/urls.py
from django.urls import path
from . import views
app_name='search'
urlpatterns=[
    path('search',views.search,name='search'),
]

Ecommerce/shop/urls.py
from django.urls import path
from shop import views
app_name='shop'
urlpatterns = [
    path('',views.home,name="home"),
    path('category',views.category,name='category'),
    path('product/<int:i>',views.product,name='product'),
    path('product_details/<int:i>',views.product_details,name="product_details"),
    path('register',views.register,name='register'),
    path('user_login',views.user_login,name='user_login'),
    path('user_logout',views.user_logout,name='user_logout'),
]

Ecommerce/cart/models.py
from django.db import models
from shop.models import Product
from django.contrib.auth.models import User

class Cart(models.Model):
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    quantity=models.IntegerField()
    date_added=models.DateTimeField(auto_now_add=True)


    def subtotal(self):
        return self.quantity*self.product.price

    def __str__(self):
        return self.product.name


class Order_table(models.Model):
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    no_of_items=models.IntegerField()
    phone=models.CharField(max_length=12)
    address=models.TextField()
    pin=models.CharField(max_length=10)
    ordered_date=models.DateTimeField(auto_now_add=True)
    order_id=models.CharField(max_length=100,blank=True)
    payment_status=models.CharField(default="pending",max_length=30)
    delivery_status=models.CharField(default="pending",max_length=30)

    def _str_(self):
        return self.user.username



class Payment(models.Model):
    name=models.CharField(max_length=100)
    amount=models.CharField(max_length=100)
    order_id=models.CharField(max_length=100,blank=True)
    razorpay_payment=models.CharField(max_length=100,blank=True)
    paid=models.BooleanField(default=False)

    def _str_(self):
        return self.name

Ecommerce/search/models.py
from django.db import models

# Create your models here.

Ecommerce/cart/views.py
from django.shortcuts import render,redirect
from shop.models import Product
from .models import Cart,Payment,Order_table
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login
import razorpay
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.models import User


@login_required
def add_to_cart(request,pk):
    p=Product.objects.get(id=pk)
    u=request.user
    try:
        cart=Cart.objects.get(user=u,product=p)
        if(p.stock>0):
            cart.quantity+=1
            cart.save()
            p.stock-=1
            p.save()

    except:
        if(p.stock):
            cart=Cart.objects.create(product=p,user=u,quantity=1)
            cart.save()
            p.stock-=1
            p.save()

    return redirect('cart:cart_views')

def cart_views(request):
    u = request.user
    cart = Cart.objects.filter(user=u)
    total = 0
    for i in cart:
        total = total + i.quantity * i.product.price
    return render(request, 'cart_views.html', {'cart': cart, 'total': total})
@login_required
def cart_decrement(request,pk):
    p=Product.objects.get(id=pk)
    u=request.user
    try:
        cart=Cart.objects.get(user=u,product=p)
        if(cart.quantity>1):
            cart.quantity-=1
            cart.save()
            p.stock+=1
            p.save()
        else:
            cart.delete()
            p.stock+=1
            p.save()

    except:
        pass

    return cart_views(request)

@login_required
def delete(request,pk):
    p=Product.objects.get(id=pk)
    u=request.user
    try:
        cart=Cart.objects.get(user=u,product=p)
        cart.delete()
        p.stock+=cart.quantity
        p.save()

    except:
        pass

    return redirect('cart:cart_views')


def place_order(request):
    if(request.method=='POST'):
        ph = request.POST.get('phone')
        a = request.POST.get('address')
        pin = request.POST.get('pin')
        u = request.user
        c = Cart.objects.filter(user=u)
        total=0
        for i in c:
            total = total+(i.quantity*i.product.price)   #total amount of cart
        total = int(total*100)
        
        # create razor pay client using ourAPI  credentails
        client=razorpay.Client(auth=('rzp_test_p9aZcQz0WqsU3d','oCDywolA2RkSadTPmBtY3ZA2'))

        #create order in razorpay
        response_payment = client.order.create(dict(amount=total,currency="INR"))


        print(response_payment)
        order_id = response_payment['id']
        order_status = response_payment['status']
        if order_status=="created":
            p = Payment.objects.create(name=u.username,amount=total,order_id=order_id)
            p.save()
            for i in c:
                o = Order_table.objects.create(user=u,product=i.product,order_id=order_id,address=a,phone=ph,pin=pin,no_of_items=i.quantity)
                o.save()
        response_payment['name']=u.username
        return render(request, 'payment.html',{'payment' : response_payment})

    return render(request,'place_order.html')


@csrf_exempt
def payment_status(request,u):
    print(request.user.is_authenticated)
    if not request.user.is_authenticated:
        u = User.objects.get(username = u)
        login(request,u)
        print(u.is_authenticated) #true


    if (request.method=="POST"):
        username = request.user
        response = request.POST #Razorpay response after payment
        # print(response)
        # print(u)
        param_dict = {
            'razorpay_order_id': response['razorpay_order_id'],
            'razorpay_payment_id': response['razorpay_payment_id'],
            'razorpay_signature' : response['razorpay_signature']

        }
        client = razorpay.Client(auth=('rzp_test_p9aZcQz0WqsU3d', 'oCDywolA2RkSadTPmBtY3ZA2'))

        try:
            status = client.utility.verify_payment_signature(param_dict)  #to check the authenticity of razorpay signature
            print(status)

            #After successful payment

            #Retrieve a payment record with particular order_id
            ord = Payment.objects.get(order_id=response['razorpay_order_id'])
            ord.razorpay_payment = response['razorpay_payment_id'] #Edits payment id response['razorpay_order_id']
            ord.paid = True #edit paid to True
            ord.save()
            # print(u)
            user = User.objects.get(username = u)
            print(user.email)
            c = Cart.objects.filter(user = user)

            #Filter the order_table details for particular user with order_id= response['razorpay_order_id']
            o = Order_table.objects.filter(user = user,order_id = response['razorpay_order_id'])
            print(o)
            for i in o:
                i.payment_status = "paid"
                i.save()
            c.delete()
            return render(request, 'payment_status.html',{'status':True})

        except:
            return render(request,'payment_status.html',{'status':False})

    return render(request, 'payment_status.html')


@login_required
def orderview(request):
    u = request.user
    customer = Order_table.objects.filter(user=u,payment_status="paid")
    return render(request,'orderview.html',{'customer' : customer,'u': u.username})

Ecommerce/search/views.py
from django.shortcuts import render
from shop.models import Product

def search(request):
    p=None
    query=""
    if(request.method=="POST"):
        query=request.POST['q']
        if query:
            p=Product.objects.filter(name__icontains=query)
    return render(request,'search.html',{'p':p,'query':query})

Ecommerce/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css" integrity="sha512-SnH5WK+bZxgPHs44uWIX+LLJAJ9/2PkPKZ5QiAj6Ta86w+fsb2TkcmfRyVX3pBnMFcV7oQPJkl9QevSCWr3W6A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-info">
  <div class="container-fluid">
    <i class="fa-brands fa-shopify"></i>
    <a class="navbar-brand" href="#">Max Buy</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'shop:home' %}">Home</a>
        </li>

          {% if user.is_authenticated %}
        <a href="{% url 'cart:cart_views' %}">
        <i class="fa-solid fa-cart-plus" style="font-size:200%;color:white;"></i></a>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'shop:category' %}">All Category</a>
        </li>

        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'shop:user_logout' %}">Logout</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'cart:orderview' %}">Your Orders</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Categories
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>

        <form class="d-flex" method="post" action="{% url 'search:search' %}">
        {% csrf_token %}
        <input class="form-control me-2" type="search" name="q" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
           </ul>
        </li>
         {% else %}
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'shop:register' %}">Register</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'shop:user_login' %}">Login</a>
        </li>
        {% endif %}
    </div>
  </div>
</nav><br>
{% block content %}

{% endblock %}
<br><br>
<div class="container-fluid bg-secondary">
    <h2>Contact:+91-9876543210</h2>
    <a href="#">Details</a>
      <h2>Gmail:abc@gmail.com</h2>
</div>
</body>
</html>

Ecommerce/templates/cart_views.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<center>
    <h4 class="text-center">Shopping Cart</h4>
<div class="container-fluid">

    <div class="row">
        <div class="col-7">
            <table class="table table-bordered">
                <tr>
                    <th colspan="6">Cart Items</th>
                </tr>
                {% for i in cart %}
                <tr>
                    <td><img src="{{i.product.image.url}}" width="150px" height="150px"></td>
                    <td>{{i.product.name}}</td>
                    <td>Product Id:{{i.product.id}}</td>
                    <td>Quantity:{{i.quantity}}<b><br>
                    Unit Price:{{i.product.price}}*{{i.quantity}}</b></td>
                    <td>Subtotal:{{i.subtotal}}</td>
                    <td>
                        {% if i.product.stock > 0 %}
                        <a href="{% url 'cart:add_to_cart' i.product.id %}"><i class="fa-solid fa-folder-plus" style="font-size:100%;color:black;"></i></a><br>
                        <a href="{% url 'cart:cart_decrement' i.product.id %}"> <i class="fa-solid fa-folder-minus" style="font-size:100%;color:black;"></i></a><br>
                        <a href="{% url 'cart:delete' i.product.id %}"> <i class="fa-solid fa-trash-arrow-up" style="font-size:100%;color:black;"></i></a>
                        {% else %}
                        <a href="{% url 'cart:cart_decrement' i.product.id %}"> <i class="fa-solid fa-folder-minus" style="font-size:100%;color:black;"></i></a><br>
                        <a href="{% url 'cart:delete' i.product.id %}"> <i class="fa-solid fa-trash-arrow-up" style="font-size:100%;color:black;"></i></a>
                        {% endif %}
                    </td>
                </tr>
                {% endfor %}
            </table>
    </div>
        <div class="col-4">
            <table class="table table-bordered">
                <tr>
                    <th colspan="4">Check Out</th>
                </tr>
                <tr>
                    <th>Total Amount:{{total}}</th>
                </tr>
            </table>
            <a  class="btn bg-warning" href="{% url 'cart:place_order' %}">PlaceOrder</a>
            <br><br>
            <a  class="btn bg-warning" href="{% url 'shop:category' %}">Continue Shopping</a>
        </div>

</div>
</center>

{% endblock %}

Ecommerce/templates/category.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container-fluid text-center mt-3 mb-3">
    <h2>Our Collections</h2>
    <p>Meesho had 209,000 users and 1.2 million orders per month in February 2019 and 563,000 users and 3.1 million orders<br>
        per month in March 2020.[10] It saw big growth during 2021 and 2022. Meesho's monthly transacting user<br>
        count rose 26 times during 2020–2022. Globally, Meesho mobile app was among the top most downloaded apps in 2021.<br>
        In 2022, Meesho had about 120 million monthly users and about 910 million orders were made through the platform.<br>
        It soon became one of India's fastest growing e-commerce platforms.</p>
    <div class="row mt-5 me-5 ms-5 mb-5 p-6">
    {% for i in c %}
        <div class="col-sm-3">
        <div class="card" style="width:20rem;">
            <img src="{{i.image.url}}" class="card-img-top" style="height:300px;"  alt="...">
        <div class="card-body">
             <h5 class="card-title">{{i.name}}</h5>
             <p class="card-text">{{i.desc}}</p>
             <a href="{% url 'shop:product' i.id %}" class="btn btn-primary">Shop Now</a>
        </div>
  </div>
</div>
    {% endfor %}
</div>

</div>
{% endblock %}

Ecommerce/templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container-fluid text-center mt-3 mb-5">
    <h2> Welcome Cart</h2>
    <div id="carouselExampleCaptions" class="carousel slide" data-bs-ride="carousel">
  <div class="carousel-indicators">
    <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
    <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1" aria-label="Slide 2"></button>
    <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2" aria-label="Slide 3"></button>
  </div>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="{% static 'images/ss1.jpg' %}" height="600px" width="45%" class="d-block w-100" alt="...">
      <div class="carousel-caption d-none d-md-block">
        <h5>FASHION CORNER</h5>
        <p>Attractive clothings for Men,Women,Teens & Kids</p>
      </div>
    </div>
    <div class="carousel-item">
      <img src="{% static 'images/ss2.jpg' %}" height="600px" width="45%" class="d-block w-100" alt="...">
      <div class="carousel-caption d-none d-md-block">
        <h5>AURA</h5>
        <p>Accessories that makes you outstanding</p>
      </div>
    </div>
    <div class="carousel-item">
      <img src="{% static 'images/ss3.jpg' %}" height="600px" width="45%" class="d-block w-100" alt="...">
      <div class="carousel-caption d-none d-md-block">
        <h5>CULINARY COLLECTION</h5>
        <p>Where Culinary dreams come to life.</p>
      </div>
    </div>
     <div class="carousel-item">
      <img src="{% static 'images/ss4.jpg' %}" height="600px" width="45%" class="d-block w-100" alt="...">
      <div class="carousel-caption d-none d-md-block">
        <h5>GADGET CENTRE</h5>
        <p>Powering your home,Empowering your Life</p>
      </div>
    </div>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>
</div>
{% endblock %}

Ecommerce/templates/login.html
<!DOCTYPE html>

{% extends 'base.html' %}
{% load static %}

{% block title %}
    <title>Login</title>
    {% endblock %}

{% block content %}

<form method="post" class="container text-center bg-warning mt-5">

    {% csrf_token %}        <!-- security feature used by django -->

    <div class="mb-3">
      <label class="form-label">Usename</label>
      <input type="text" class="form-control" name="u">
    </div>
    <div class="mb-3">
      <label class="form-label">Password</label>
      <input type="password" class="form-control" name="p">
    </div>

    <div>
    <input type="submit">
    </div>
</form>

{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}

{% endblock %}

</body>
</html>

Ecommerce/templates/orderview.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container">

    <div class="row" style="margin-top:100px">
        <h4 class="text-center fw-bold">{{u}}'s Orders</h4><br><br>
        {% for i in customer %}
        <div class="col-4 p-4">
            <img src="{{i.product.image.url }}" height="300px" width="100%">
        </div>
        <div class="col-5 p-4" style="align-item:center;">
<!--            <hr class="w-25 border border-2 border-dark mx-auto">-->
            <h5><b>Product:</b>{{i.product.name}}</h5>
            <h5><b>Price:</b>{{i.product.price}}</h5>
            <h5><b>Address:</b>{{i.address}}</h5>
            <h5><b>Contact:</b>{{i.phone}}</h5>
            <h5><b>No. of Items:</b>{{i.no_of_items}}</h5>
            <h5><b>Ordered date:</b>{{i.ordered_date}}</h5>
            <h5><b>Status:</b>{{i.delivery_status}}</h5>

        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

Ecommerce/templates/payment.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<br><br><br>
<center>
<h2>Payment Page</h2>

    <div class="bg-light mt-3">
        <form action="http://127.0.0.1:8000/cart/payment_status/{{payment.name}}" method="POST">
            {% csrf_token %}
    <script
        src="https://checkout.razorpay.com/v1/checkout.js"
        data-key="rzp_test_p9aZcQz0WqsU3d"
        data-amount="{{payment.amount}}"
        data-currency="{{payment.currency}}"
        data-order_id="{{payment.id}}"
        data-buttontext="Pay with Razorpay"
        data-name="MaxBuy Shop"
        data-description="A Wild Sheep Chase is the third novel by Japanese author Haruki Murakami"
        data-image="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQnnCrQobO6g86R2ElEj5PAf-D8bTk5asVTwQ&s"
        data-prefill.name="Gaurav Kumar"
        data-prefill.email="gaurav.kumar@example.com"
        data-theme.color="#C40C0C"
    ></script>
    <input type="hidden" custom="Hidden Element" name="hidden"/>
    </form>
     </div>
</center>
{% endblock %}

Ecommerce/templates/payment_status.html
{% extends 'base.html' %}

{% load static %}
{% block content %}
{% if status == True %}
<link rel="stylesheet" href="{% static 'css/payment_done.css' %}">
<div class="container-fluid">
  <div class="success">&#10004;</div>
  <h1>Order Placed</h1>
  <h2 class="title">Payment Successful</h2>
  <a href="{% url 'home.html' %}" class="button">Continue Shopping</a>
  {% else %}
    <h4>Payment is not successful</h4>

  {% endif %}
  </div>
{% endblock %}

Ecommerce/templates/place_order.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<form method="post" class="container text-center bg-warning text-info fw-bold mt-5">

    {% csrf_token %}
     <h2>Enter Details</h2>
    <div class="mb-3">
      <label class="form-label">Phone Number</label>
      <input type="number" class="form-control" name="phone">
    </div>
    <div class="mb-3">
      <label class="form-label">Address</label>
      <input type="text" class="form-control" name="address">
    </div>
    <div class="mb-3">
      <label class="form-label">Pin Number</label>
      <input type="number" class="form-control" name="pin">
    </div>
    <div>
    <input type="submit">
    </div>

</form>

</div>

{% endblock %}

Ecommerce/templates/product.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<center>
<h2>Products</h2>
<br>
<div class="row">
    <img src="{{c.image.url}}" height="800px" width="100%">
</div>
<div class="container-fluid text-center">
    <div class="row mt-5 ms-3">
        <div class="col-md-12">
            <h1 class="text-center fw-bold">{{c.name}}</h1>
            <p style="">{{c.desc}}</p>
        </div>
    </div>
</div>
<div class="container-fluid">
    <div class="row">
        {% for i in p %}
        <div class="col-sm-3">
        <div class="card" style="width: 20rem;">
        <img src="{{i.image.url}}" style="height:300px;" class="card-img-top" alt="...">
            <div class="card-body">
                <h5 class="card-title">{{i.name}}</h5>
                <h3 class="card-text">{{i.price}}</h3>
                <a href="{% url 'shop:product_details' i.id %}" class="btn btn-primary">Buy Now</a>
            </div>
        </div>
        </div>
    {% endfor %}
    </div>
</div>
    </center>
{% endblock %}

Ecommerce/templates/product_details.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container text-center mt-5 mb-5">
    <h2>Product Details</h2>
</div>
<div class="container bg-danger">
    <div class="row">
        <div class="col">
            <img src="{{p.image.url}}" height="400px" width="75%">
        </div>
        <div class="col">
            <h2>{{p.name}}</h2>
            <h4>{{p.desc}}</h4>
            <h2>{{p.price}}</h2>
            <h3>{{p.stock}}</h3>
            {% if user.is_superuser == True %}
                {% if p.stock > 0 %}
                    <h3 class="text-success">Product in Stock</h3>
                    <a style="text-decoration:none" href="{% url 'admin:index' %}" class="btn_1">Add Stock</a>
                {% else %}
                    <h3 class="text-danger">Out of Stock</h3>
                    <a style="text-decoration:none" href="{% url 'admin:index' %}" class="btn_1">Add Stock</a>
                {% endif %}
            {% else %}
                {% if p.stock > 0 %}
                    <a href="{% url 'cart:add_to_cart' p.id %}" class="btn_1 text-warning">Add to Cart</a>
                {% else %}
                    <h3 class="text-secondary">Out of Stock</h3>
                {% endif %}
            {% endif %}
      <h3>Product Details<i style="#" class="fa fa-indent"></i> </h3>
      <p style="#">{{p.desc}}</p>

    </div>
  </div>
</div>

{% endblock %}

Ecommerce/templates/register.html
{% extends 'base.html' %}
{% load static %}
  <title>Register</title>


{% block content %}

<form method="post" class="container text-center bg-warning text-secondary fw-bold mt-5 mb-5">

    {% csrf_token %}

    <div class="mb-3">
      <label class="form-label">Username</label>
      <input type="text" class="form-control" name="u">
    </div>
    <div class="mb-3">
      <label class="form-label">Password</label>
      <input type="password" class="form-control" name="p">
    </div>
    <div class="mb-3">
      <label class="form-label">Confirm_Password</label>
      <input type="password" class="form-control" name="c">
    </div>
    <div class="mb-3">
      <label class="form-label">First_name</label>
      <input type="text" class="form-control" name="f">
    </div>
    <div class="mb-3">
      <label class="form-label">Last_name</label>
      <input type="text" class="form-control" name="l">
    </div>
    <div class="mb-3">
      <label class="form-label">Email</label>
      <input type="email" class="form-control" name="e">
    </div>


    <div>
    <input type="submit">
    </div>

</form>


{% endblock %}

Ecommerce/templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<title>Search</title>

<h2 class="mt-3 mb-3">Search result of {{query}}</h2>


<div class="container mt-3">
  {% if p %}
  <div class="row">
    {% for i in p %}
      <div class="col-4 mt-4">
        <div class="card" style="width: 18rem;">
          <a href="{% url 'shop:product_details' i.id %}">
            <img src="{{i.image.url}}" class="card-img-top" height="250px" width="150px" alt="..." ></a>
          <div class="card-body">
            <center>
              <h5 class="card-title">{{i.name}}</h5>
              <p class="card-text">{{i.price}}</p>

            </center>
          </div>
        </div>
      </div>
    {% endfor %}
  </div>
  {% else %}
  <div class="row">
    <div class="col-md-12" style="">
      <h4 class="fn-bold text-center">No Search Found..</h4>
    </div>
    {% endif %}
  </div>
</div>


{% endblock %}